### ISSUE TITLE
Add Boost settings to spaces query

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot-hub#822]
```[tasklist]
### Tasks
- [ ] https://github.com/snapshot-labs/snapshot/pull/4616
- [ ] https://github.com/snapshot-labs/snapshot.js/pull/976
- [x] Add boost settings to graphql schema
- [x] By default it should return ```{enabled: true, bribeEnabled: false}```
```
